name: veltrik
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.4
  syncfusion_flutter_pdfviewer: ^33.2.3
  google_fonts: ^8.0.2
  file_picker: ^10.3.10 
  flutter_dotenv: ^6.0.1
  shimmer: ^3.0.0
  screen_protector: ^1.5.1
  device_info_plus: ^12.4.0 
  onesignal_flutter: ^5.1.6 # DITAMBAHKAN UNTUK PUSH NOTIFICATION

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png" 
  adaptive_icon_background: "#102140" 
  adaptive_icon_foreground: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets: 
   - .env
   - assets/images/icon.png